name = "togoo"
main = "./worker/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
preview_urls = true

[assets]
binding = "ASSETS"
not_found_handling = "none"

[images]
binding = "IMAGES"

[[d1_databases]]
binding = "DB"
database_name = "togoo-db"
database_id = "1a9f1ff3-1ab0-4ca3-91eb-d4a803ce6880"
migrations_dir = "drizzle/migrations"
