name = "togoo"
main = "./worker/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
preview_urls = true

[assets]
binding = "ASSETS"
not_found_handling = "none"

[images]
binding = "IMAGES"

[[d1_databases]]
binding = "DB"
database_name = "togoo-db"
database_id = "7041fef3-b659-491d-b66f-7d14835a547b"
migrations_dir = "drizzle/migrations"
