name = "togoo"
main = "./worker/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
preview_urls = true

[assets]
binding = "ASSETS"
not_found_handling = "none"

[images]
binding = "IMAGES"

[[d1_databases]]
binding = "DB"
database_name = "togoo-db"
database_id = "6ef22bb4-76f5-46e4-8980-42829808248e"
migrations_dir = "drizzle/migrations"
